### ISSUE TITLE
NullPointerException while rendering Railgun in Transmutation Table (ProjectE)

### ISSUE THREAD

**Issue by expeehaa** [CJ-MC-Mods/IBHSTD#67] opened 2019-05-18 21:03 UTC
#### Overloaded Version: 0.0.55

I crafted a Railgun and put it in my inventory. After adding the Railgun to my Transmutation Table (ProjectE) my game crashed and it crashed every time I tried to open the Transmutation Table GUI until it got removed from the ProjectE-learned-item-storage (or however it is called).
Though it is caused by ProjectE I think this might not be directly related to it but rather the displaying of the item which might happen in any other mod doing equivalent things. Either way I hope this isn't too complicated to fix.
The line causing the problem is [here](https://github.com/CJ-MC-Mods/Overloaded/blob/1.12/src/main/java/com/cjm721/overloaded/storage/itemwrapper/IntEnergyWrapper.java#L87) and because it is the energy of the item I would suggest an energy default value of 0 if such an exception is thrown. 

Here is the [crash log](https://github.com/CJ-MC-Mods/Overloaded/files/3194496/crash.txt)

**Comment by cjm721** [comment] 2019-05-18 23:55
Duplicate of #65.

**Closed as completed by cjm721** 2019-05-18 23:55 UTC
