### ISSUE TITLE
Infinite storage blocks are too easy to break

### ISSUE THREAD

**Issue by Machine-Maker** [CJ-MC-Mods/IBHSTD#58] opened 2019-04-26 08:17 UTC
#### Minecraft Version: 1.12.2
Not really a bug report.

The infinite blocks that lose all stored items/fluids/energy when broken should take a while to break. Currently even with a stone pickaxe they break very quickly and can accidentally be broken. 

What would be even better would be a tool to toggle an indestructible state to prevent any accidental breakages.

**Comment by sironin** [comment] 2019-04-26 10:10
Not saying they shouldn't be harder to break (maybe be at least as hard to break as the default ingredients), but as a reminder the mod comes with a tool that insta-breaks everything.  The exception being blocks specifically protected/unbreakable.  So if you are playing a pack that has something like RFTools' block protector, you can use it to prevent your vital machines from accidentally being broken.

I am not the developer for this mod, I am simply offering my thoughts.

**Comment by cjm721** [comment] 2019-04-27 21:42
Closing as basically a duplicate of #32 and opposite request of #20 See my comments there if you want more game play explanations.

**Closed as completed by cjm721** 2019-04-27 21:42 UTC
