### ISSUE TITLE
[Feature Request] Rail gun Ammo sound and Firing effect

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/IBHSTD#85] opened 2019-09-09 19:03 UTC
Rail gun also looks nice but needs ammo rail guns do use power for the most part but they also need some type of ammo simple iron ingots turn into iron slugs that can be added to a clip to hold them in like a normal gun also the rail gun makes no sound in this mod or any Firing effect for Reference https://youtu.be/BzHf5n5K5gw?t=108 this even looks like the one mega made lol also it should have a cool down a few secs each time you fire it but if you fire it to much it needs a Longer 1 min cool down time due to overheating.

**Comment by cjm721** [comment] 2019-09-10 01:14
Duplicate of #45

**Closed as completed by cjm721** 2019-09-10 01:14 UTC
Labels: enhancement
