### ISSUE TITLE
Multi armor model problem #2

### ISSUE THREAD

**Issue by OutFang** [CJ-MC-Mods/IBHSTD#117] opened 2022-12-20 02:47 UTC
( since the first issue is closed i thought you wouldn't be able to see it so i'm putting it back here ) 
The crash i sent you is caused by an armor stand but the problem is that the armor stand won't render because the multi armor helmet is on it . 
I crafted the multi armor and everything was fine as long as it wasn't on me or on the armor stand , thats why i said the " multi armor model" . 

Here is an other crash from when it was on my character : 
https://pastebin.com/yXgv4WmL

sorry to disturb you and thanks again for your help

_Originally posted by @OutFang in https://github.com/CJ-MC-Mods/Overloaded/issues/116#issuecomment-1358764735_

**Comment by cjm721** [comment] 2022-12-20 05:00
Duplicate of #116

**Closed as completed** 2022-12-20 05:01 UTC
