### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Serzh812** [CJ-MC-Mods/IBHSTD#89] opened 2019-12-18 15:07 UTC
#### Overloaded Version: <1.14.4-0.0.78>
is it possible to combine multi tool with tank Storage mod ?
https://www.curseforge.com/minecraft/mc-mods/dank-storage

**Comment by cjm721** [comment] 2019-12-18 17:17
Duplicate of #88

**Closed as completed by cjm721** 2019-12-18 17:17 UTC
