### ISSUE TITLE
Hyper fluid sender not sending liquids.

### ISSUE THREAD

**Issue by G1R-Productions** [CJ-MC-Mods/IBHSTD#82] opened 2019-08-31 08:07 UTC
#### Overloaded Version: <1.12.2-0.0.57>

Hyper fluid sender not working. The fluid sender is properly linked to a fluid receiver which is attached to an infinity tank. The tank attached to the fluid sender fills with liquid but the infinity tank attached to the receiver never fills up with any liquid. Tested with both Water and Lava.

**Comment by cjm721** [comment] 2019-08-31 17:37
Update, this was fixed in version 58 and is also a duplicate of #71 from two months ago

**Closed as completed by cjm721** 2019-08-31 17:37 UTC
