### ISSUE TITLE
[Feature Request] Ray Gun Should Sound and shoot like a Ray Gun

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/IBHSTD#84] opened 2019-09-09 18:54 UTC
So the ray gun has the looks down right mega did a Great job in that area but it does not shoot like or sound like a ray gun here is a sound thats free https://www.youtube.com/watch?v=cYoQ9R19PnI tho i think the sound should be longer not so short more like https://www.youtube.com/watch?v=EKsy8aoilpw and it would shoot out small green rings when it fires.

**Comment by cjm721** [comment] 2019-09-10 01:14
Duplicate of #45

**Closed as completed by cjm721** 2019-09-10 01:14 UTC
Labels: enhancement
