### ISSUE TITLE
Instant Furnace not smelting

### ISSUE THREAD

**Issue by aaronhowser1** [CJ-MC-Mods/IBHSTD#110] opened 2021-10-25 11:50 UTC
#### Overloaded Version: Overloaded-1.16.4-0.0.94

![image](https://user-images.githubusercontent.com/15698722/138689713-fc75ec58-589b-41d0-858e-acca6187e6e1.png)
This is just sitting here not doing anything

![image](https://user-images.githubusercontent.com/15698722/138689739-86947eba-b6d5-4e12-93e3-b1c869d02ebd.png)
I have this set up to pull all non-ores (see #109) out and into the drawers, but it just stops smelting items.

https://user-images.githubusercontent.com/15698722/138689909-ee5d4871-dd0e-4a80-b22f-ae383d792cfd.mp4

It only actually remembers to smelt when I take an item out, and then stops working pretty much instantly

**Comment by cjm721** [comment] 2021-11-07 10:07
I cannot reproduce using AE2 and putting a few hundred million items through (1 stack per tick). 

Going to need to see more about your setup + try using other mods to insert / extract as it may be something with how the particular mod inserts or extracts.

**Comment by cjm721** [comment] 2021-11-25 00:21
Will close this bug soon if don't hear back. Feel free to re-open / create new bug with more information if past the closure.

**Comment by aaronhowser1** [comment] 2021-11-26 05:05
This has a different problem now, using AE2. They suddenly stopped accepting items, and I had to jumpstart them by putting something in.

https://user-images.githubusercontent.com/15698722/143529669-f1931b96-39c5-4a75-a298-1929ee28eeb6.mp4

**Comment by cjm721** [comment] 2021-11-26 12:58
Going to need a lot more details about the environment you are in. If it is not reproducible with just Overloaded + an IO mod (AE2 / Mekanism) then I have to assume you have some performance mod (mohist / tickrate / etc) that is either breaking the standard item insert logic, or is putting the tile to sleep.

IE:
* Mods Installed (Mod Pack)
* Forge Version

**Comment by aaronhowser1** [comment] 2021-11-29 14:04
This is FTB University 1.16, which is using Forge 36.2.4

**Comment by cjm721** [comment] 2021-11-30 05:10
Not able to reproduce still. Is your initial setup not doing it anymore? Thinking about the AE2 one it might actually be working just inserting and extracting on the same tick so you don't see it, but once you add in the single item offsets the pattern. I been looking at the output and input to see the flows.

**Comment by cjm721** [comment] 2021-11-30 05:11
Also guess I never did ask you doing this in single player or multiplayer

**Comment by cjm721** [comment] 2021-11-30 05:12
4 Methods and I let them run for an hour and they were still processing at the end.
![image](https://user-images.githubusercontent.com/2738614/143989414-00b0dafb-a3dd-45ca-b4d0-95b44fa58ea4.png)

**Comment by aaronhowser1** [comment] 2021-12-02 07:39
I tore down my initial setup, but yours looks basically the same as mine so I assume it just works now. Maybe it had something to do with #109, which has been fixed?

**Comment by cjm721** [comment] 2021-12-09 09:35
Going to have to assume that. Closing this bug if you find a way to cause it again create re-open this.

**Closed as completed by cjm721** 2021-12-09 09:35 UTC
Labels: more info required
